name: nuz

on:
  push:
    branches:
      - master
      - develop
      - next
  pull_request:
    branches:
      - master
      - develop
      - next

jobs:
  lint:
    name: Lint - ${{ matrix.os }} - Node v${{ matrix.node-version }}

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}

      - name: Use latest Yarn
        run: sudo npm i -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn run lint

      - name: Check commit message
        uses: wagoid/commitlint-github-action@v1

  test:
    name: Test - ${{ matrix.os }} - Node v${{ matrix.node-version }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [10.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Git
        if: matrix.os == 'windows-latest'
        run: git config --global core.autocrlf input

      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use latest Yarn on ubuntu/macos
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: sudo npm i -g yarn

      - name: Use latest Yarn on windows
        if: matrix.os == 'windows-latest'
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Try to build with Typescript
        run: yarn run test:types

      - name: Run unit tests
        run: yarn run test:unit -- --ci

  Deploy:
    if: github.ref == 'refs/heads/next'
    needs: 
      - test
      - lint

    name: Deploy - ${{ matrix.os }} - Node v${{ matrix.node-version }}

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      website-directory: website

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}

      - name: Use latest Yarn
        run: sudo npm i -g yarn

      - name: Install dependencies in website directory
        working-directory: ${{ env.website-directory }}
        run: yarn install

      - name: Build document website
        working-directory: ${{ env.website-directory }}
        env:
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
        run: yarn run build

      - name: Deploy document website
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: ./website/build
          commit_message: 'chore: deploy document website ${{ github.event.head_commit.id }}'
          # cname: docs.nuz.app
        
